services:
  mongo_server:
    image: mongo
    container_name: mongo_server
    restart: always    
    ports:
      - 27017:27017
    # volumes:
    #   - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      my-bridge-network:
        ipv4_address: 192.168.1.2

networks:
  my-bridge-network:
    external: true